export_file_url = 'https://www.dropbox.com/s/ks48qkppr6kyqj7/export.pk1?raw=1'
export_file_name = 'export.pk1'


classes = ['AFRICAN CROWNED CRANE','AFRICAN FIREFINCH','ALBATROSS','ALEXANDRINE PARAKEET','AMERICAN AVOCET','AMERICAN BITTERN','AMERICAN COOT','AMERICAN GOLDFINCH','AMERICAN KESTREL','AMERICAN PIPIT','AMERICAN REDSTART','ANHINGA','ANNAS HUMMINGBIRD','ANTBIRD','ARARIPE MANAKIN','ASIAN CRESTED IBIS','BALD EAGLE','BALI STARLING','BALTIMORE ORIOLE','BANANAQUIT']
path = Path(__file__).parent
